name: Sync and Release

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * 1'  # 每周一检查更新

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          upstream_sync_branch: main
          upstream_sync_repo: snailyp/gemini-balance
          access_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create release if changes
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          VERSION=$(date +%Y.%m.%d)
          gh release create v$VERSION --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
